version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # `> log.txt || type log.txt` is for muting the output unless there is an error
  - haxelib install travix > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hxcs   > log.txt || type log.txt && cmd /C exit 1
  - haxelib list
  - haxelib run travix install
  - ps: $env:HXCS_PATH = haxelib path hxcs | Select-Object -First 1
  - copy "C:\Program Files (x86)\Mono\lib\mono\4.0\System.Xml.Linq.dll" "%HXCS_PATH%\netlib\net-40\"
  - copy "C:\Program Files (x86)\Mono\lib\mono\4.0\System.Xml.dll" "%HXCS_PATH%\netlib\net-40\"
  - git submodule sync && git submodule update --init --recursive && git submodule status
  - cd sdk 
  - ps: $content = get-content build.open-xml-sdk.cmd | select-string -pattern "xunit`.console`.exe" -notmatch
  - ps: $content | set-content build.open-xml-sdk.cmd -Force
  - build.open-xml-sdk.cmd
  - cd ..

build: off
test_script:
  - haxe validator.hxml
  - haxelib run travix neko