name: CI
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get install -qqy nuget mono-complete
      - run: yarn global add lix --prefix /usr/local
      - run: yarn
      - run: lix download
      - run: cp lib/System.Xml.Linq.dll lib/System.Xml.dll "$(haxelib path hxcs | head -n 1)/netlib/net-40/"
      - run: nuget restore Open-XML-SDK.sln
        working-directory: ./sdk
      - run: xbuild /p:Configuration=Release Open-XML-SDK.sln
        working-directory: ./sdk
      - run: haxe validator.hxml
      - run: lix run travix node
